apiVersion: v1
kind: ConfigMap
metadata:
  name: jira-config
  namespace: telegram-pb
data:
  story-points-field: "customfield_10022"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: voting-config
  namespace: telegram-pb
data:
  redis-url: "redis://redis:6379/0"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
  namespace: telegram-pb
data:
  supported-topics: "{}"
